services:
  api:
    build: ./backend
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE_CONNECTION_URI: ${DATABASE_CONNECTION_URI_PYTHON}
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - backend

networks:
  backend:
