"""criando as tabelas

Revision ID: 5216023b5f76
Revises: 
Create Date: 2025-10-15 22:14:11.899791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5216023b5f76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('unidade_medida', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('kcal', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('proteinas', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('gordura', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('acucar', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('carboidratos', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('unidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_refeicao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_refeicao_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_refeicao_id'], ['tipos_refeicao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardapios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.Column('data_check', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardapio_alimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cardapio_id', sa.Integer(), nullable=True),
    sa.Column('alimento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cardapio_alimentos')
    op.drop_table('checks')
    op.drop_table('cardapios')
    op.drop_table('horarios')
    op.drop_table('usuarios')
    op.drop_table('tipos_refeicao')
    op.drop_table('alimentos')
    # ### end Alembic commands ###
