"""adcionando coluna principal no Cardapio_models

Revision ID: 5b6843193393
Revises: 780456981e48
Create Date: 2025-10-16 18:31:44.636236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6843193393'
down_revision: Union[str, Sequence[str], None] = '780456981e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardapios', sa.Column('principal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardapios', 'principal')
    # ### end Alembic commands ###
