"""adiciona timestamps criado_em e atualizado_em em usuarios

Revision ID: 5b99509c3ef9
Revises: df0224deb319
Create Date: 2025-11-08 09:59:32.973496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b99509c3ef9'
down_revision: Union[str, Sequence[str], None] = 'df0224deb319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ...
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('criado_em', sa.DateTime(), nullable=False))
    op.add_column('usuarios', sa.Column('atualizado_em', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'atualizado_em')
    op.drop_column('usuarios', 'criado_em')
    # ### end Alembic commands ###
