"""adcionando coluna horario_refeicao na tabela Horario

Revision ID: 780456981e48
Revises: 5216023b5f76
Create Date: 2025-10-16 14:34:24.518188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780456981e48'
down_revision: Union[str, Sequence[str], None] = '5216023b5f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horarios', sa.Column('horario_refeicao', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horarios', 'horario_refeicao')
    # ### end Alembic commands ###
